import React, { useState } from 'react';
import axios from 'axios';

const CREDS_KEY = 'flowforge.platformCredentials.v1';

function readStoredCredentials() {
  try {
    const raw = localStorage.getItem(CREDS_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

const PLATFORM_FILE_PATHS = {
  github: '.github/workflows/ci.yml',
  gitlab: '.gitlab-ci.yml',
  bitbucket: 'bitbucket-pipelines.yml',
};

export default function PushToRepoModal({ platform, owner, repo, branch, yamlContent, cicdPlatform, onClose, onSuccess }) {
  const [mode, setMode] = useState('pr');
  const [prBranch, setPrBranch] = useState(`flowforge/pipeline-${Date.now()}`);
  const [prTitle, setPrTitle] = useState('ci: add FlowForge pipeline config');
  const [commitMessage, setCommitMessage] = useState('ci: add pipeline config via FlowForge');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const allCreds = readStoredCredentials();
  const credentials = allCreds[platform] || {};

  const resolvedFilePath = PLATFORM_FILE_PATHS[cicdPlatform] || PLATFORM_FILE_PATHS[platform] || '.github/workflows/ci.yml';

  const handlePush = async () => {
    setLoading(true);
    setError('');
    try {
      const { data } = await axios.post('/api/repo/push-pipeline', {
        platform,
        credentials,
        owner,
        repo,
        branch,
        yamlContent,
        filePath: resolvedFilePath,
        commitMessage,
        mode,
        prBranch: mode === 'pr' ? prBranch : undefined,
        prTitle: mode === 'pr' ? prTitle : undefined,
        prDescription: mode === 'pr' ? 'Pipeline configuration generated by FlowForge.' : undefined,
        targetBranch: branch,
      });
      onSuccess(data);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to push to repository');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--ff-overlay)]">
      <div className="w-full max-w-lg mx-4 rounded-2xl border border-[var(--ff-card-border)] bg-[var(--ff-sidebar-bg)] shadow-xl p-6 space-y-5">
        {/* Header */}
        <div className="flex items-start justify-between gap-3">
          <div>
            <h3 className="text-base font-semibold text-[var(--ff-text)]">Push to Repository</h3>
            <p className="text-xs text-[var(--ff-muted)] mt-0.5">
              {repo} · {branch} · <span className="font-mono">{resolvedFilePath}</span>
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-[var(--ff-muted)] hover:text-[var(--ff-text)] transition-colors"
            aria-label="Close"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
              <path d="M3 3l10 10M13 3L3 13"/>
            </svg>
          </button>
        </div>

        {/* Mode toggle */}
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => setMode('pr')}
            className={`rounded-xl border px-4 py-3 text-left transition-all ${
              mode === 'pr'
                ? 'border-[var(--ff-border-strong)] bg-[var(--ff-accent-soft)]'
                : 'border-[var(--ff-card-border-strong)] bg-[var(--ff-card-bg)] hover:border-[var(--ff-border-strong)]'
            }`}
          >
            <p className="text-sm font-semibold text-[var(--ff-text)]">Open PR / MR</p>
            <p className="text-xs text-[var(--ff-muted)] mt-0.5">Create a branch and open a pull request for review</p>
          </button>
          <button
            onClick={() => setMode('direct')}
            className={`rounded-xl border px-4 py-3 text-left transition-all ${
              mode === 'direct'
                ? 'border-[var(--ff-border-strong)] bg-[var(--ff-accent-soft)]'
                : 'border-[var(--ff-card-border-strong)] bg-[var(--ff-card-bg)] hover:border-[var(--ff-border-strong)]'
            }`}
          >
            <p className="text-sm font-semibold text-[var(--ff-text)]">Commit directly</p>
            <p className="text-xs text-[var(--ff-muted)] mt-0.5">Push straight to <span className="font-mono text-[10px]">{branch}</span></p>
          </button>
        </div>

        {/* PR mode fields */}
        {mode === 'pr' && (
          <div className="space-y-3">
            <div>
              <label className="text-xs uppercase tracking-[0.14em] text-[var(--ff-muted)] block mb-1.5">PR Title</label>
              <input
                type="text"
                value={prTitle}
                onChange={(e) => setPrTitle(e.target.value)}
                className="ff-input px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="text-xs uppercase tracking-[0.14em] text-[var(--ff-muted)] block mb-1.5">New Branch Name</label>
              <input
                type="text"
                value={prBranch}
                onChange={(e) => setPrBranch(e.target.value)}
                className="ff-input px-3 py-2 text-sm font-mono"
              />
            </div>
          </div>
        )}

        {/* Direct mode fields */}
        {mode === 'direct' && (
          <div>
            <label className="text-xs uppercase tracking-[0.14em] text-[var(--ff-muted)] block mb-1.5">Commit Message</label>
            <input
              type="text"
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              className="ff-input px-3 py-2 text-sm"
            />
          </div>
        )}

        {error && (
          <p className="text-sm text-[var(--ff-danger)] bg-[var(--ff-danger)]/10 border border-[var(--ff-danger)]/20 rounded-lg px-3 py-2">
            {error}
          </p>
        )}

        {/* Actions */}
        <div className="flex items-center gap-3 pt-1">
          <button
            onClick={handlePush}
            disabled={loading || !yamlContent}
            className="flex-1 ff-btn-primary rounded-xl py-2.5 text-sm font-semibold disabled:opacity-50"
          >
            {loading ? 'Pushing...' : mode === 'pr' ? 'Create Branch & Open PR' : 'Commit to Repository'}
          </button>
          <button
            onClick={onClose}
            className="ff-btn-secondary rounded-xl px-4 py-2.5 text-sm font-medium"
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
